apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: keycloak-external-alias
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - identity{{ if .Values.global.envTag }}-{{ .Values.global.envTag }}{{ end }}.{{ .Values.global.domain }}
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 8080
    name: http-8080
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: keycloak-service.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak-external-redirect
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - identity{{ if .Values.global.envTag }}-{{ .Values.global.envTag }}{{ end }}.{{ .Values.global.domain }}
  http:
  - route:
    - destination:
        host: keycloak-service.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
