apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: backoffice-bff-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - backoffice-bff.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: backoffice-bff.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: backoffice-ui-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - backoffice-ui.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: backoffice-ui.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: storefront-bff-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - storefront-bff.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: storefront-bff.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: storefront-ui-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - storefront-ui.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: storefront-ui.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: swagger-ui-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - swagger-ui.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: swagger-ui.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: cart-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - cart.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: cart.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: customer-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - customer.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: customer.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: inventory-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - inventory.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: inventory.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: media-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - media.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: media.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: order-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - order.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: order.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: product-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - product.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: product.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: search-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - search.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: search.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tax-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - tax.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: tax.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sampledata-retry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - sampledata.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
        retryOn: 5xx,connect-failure,refused-stream,gateway-error
      route:
        - destination:
            host: sampledata.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 80
