kind: Secret
apiVersion: v1
metadata:
  name: user-credentials-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
stringData:
  {{- $files := .Files }}
  users: |-
  {{- range tuple "filerealm/users" }}
    {{ $files.Get . }}
  {{- end }}
  users_roles: |-
    superuser:yas
