apiVersion: v2
name: yas-umbrella
description: Umbrella chart for YAS CI-CD containing data layer and app layer
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: backoffice-bff
  version: '*'
  repository: file://../backoffice-bff
- name: backoffice-ui
  version: '*'
  repository: file://../backoffice-ui
- name: cart
  version: '*'
  repository: file://../cart
- name: customer
  version: '*'
  repository: file://../customer
- name: inventory
  version: '*'
  repository: file://../inventory
- name: media
  version: '*'
  repository: file://../media
- name: order
  version: '*'
  repository: file://../order
- name: product
  version: '*'
  repository: file://../product
- name: sampledata
  version: '*'
  repository: file://../sampledata
- name: search
  version: '*'
  repository: file://../search
- name: storefront-bff
  version: '*'
  repository: file://../storefront-bff
- name: storefront-ui
  version: '*'
  repository: file://../storefront-ui
- name: swagger-ui
  version: '*'
  repository: file://../swagger-ui
- name: tax
  version: '*'
  repository: file://../tax
- name: yas-configuration
  version: '*'
  repository: file://../yas-configuration
- name: postgres
  version: '*'
  repository: file://../postgresql
- name: pgadmin
  version: '*'
  repository: file://../pgadmin
- name: zookeeper
  version: '*'
  repository: file://../zookeeper
- name: kafka-cluster
  version: '*'
  repository: file://../kafka-cluster
- name: elasticsearch-cluster
  version: '*'
  repository: file://../elasticsearch-cluster
- name: keycloak
  version: '*'
  repository: file://../keycloak
- name: akhq
  version: 0.2.3
  repository: https://akhq.io/
- name: redis
  version: 19.6.4
  repository: https://charts.bitnami.com/bitnami
