apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.passwordSecret" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
type: Opaque
data:
  pgadmin-password: {{ default "admin" .Values.pgadmin.password | b64enc | quote }}
